### ISSUE TITLE
Problems with sourcegen.sh

### ISSUE THREAD

**Issue by maksimil** [rust-rdom/rust-rdom#44]
I found out that `sourcegen.sh` cannot be ran if `rdom` isn't compiled. Sourcegen is separate from rdom, imo. So I think this is unwanted behavior.

**Comment by maksimil** [comment]
Also `sourcegen` is a bit slow, so I might become a contributor to that project too, can't promise anything though.

**Comment by philip-peterson** [comment]
@maksimil That would be cool. I work at the company that runs that repo so I could probably merge your PRs.
