### ISSUE TITLE
Sourcegen rewrite

### ISSUE THREAD

**Issue by maksimil** [rust-rdom/rust-rdom#47]
Checklist for macros that need rewriting using `sourcegen`

- [x] SandboxMember mixin
- [ ] ParentNode
- [ ] NodeBehavior
- [ ] concrete nodes
- [ ] node contents
- [ ] html elements

**Comment by philip-peterson** [comment]
Closing this out because I think we should not plan to replace most of the codebase with sourcegen. Macros work fine for now, and if something becomes too overbearing we should revisit this then.
